In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

2023-05-12 16:17:50.931316: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-12 16:17:51.679299: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-12 16:17:51.683932: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-12 16:17:53.578013: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [6]:
df = pd.read_excel('dataFrame.xlsx')

In [3]:
scaler = MinMaxScaler(feature_range=(0,1))
data = scaler.fit_transform(df)
data

array([[0.61904762, 0.57142857, 0.61904762, 0.52380952, 0.52380952,
        0.47619048, 0.52380952, 0.57142857],
       [0.57142857, 0.61904762, 0.52380952, 0.52380952, 0.47619048,
        0.52380952, 0.57142857, 0.57142857],
       [0.61904762, 0.52380952, 0.52380952, 0.47619048, 0.52380952,
        0.57142857, 0.57142857, 0.61904762],
       [0.52380952, 0.52380952, 0.47619048, 0.52380952, 0.57142857,
        0.57142857, 0.61904762, 1.        ],
       [0.52380952, 0.47619048, 0.52380952, 0.57142857, 0.57142857,
        0.61904762, 1.        , 0.76190476],
       [0.47619048, 0.52380952, 0.57142857, 0.57142857, 0.61904762,
        1.        , 0.76190476, 0.57142857],
       [0.52380952, 0.57142857, 0.57142857, 0.61904762, 1.        ,
        0.76190476, 0.57142857, 0.85714286],
       [0.57142857, 0.57142857, 0.61904762, 1.        , 0.76190476,
        0.57142857, 0.85714286, 0.85714286],
       [0.57142857, 0.61904762, 1.        , 0.76190476, 0.57142857,
        0.85714286, 0.857142

In [15]:
x_train, x_test, y_train, y_test = train_test_split(data[:,:-1], data[:,-1], test_size=0.2)
x_train.shape

(40, 7)

In [8]:
# Membuat model LSTM
model = Sequential()
model.add(LSTM(32, input_shape=(7, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

2023-05-12 16:55:02.724645: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-05-12 16:55:02.726515: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-05-12 16:55:02.728282: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [10]:
# Melatih model
model.fit(x_train, y_train, epochs=100, batch_size=32, verbose=2)

Epoch 1/100


2023-05-12 16:55:30.183936: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-05-12 16:55:30.185586: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-05-12 16:55:30.186878: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

2/2 - 2s - loss: 0.1779 - 2s/epoch - 1s/step
Epoch 2/100
2/2 - 0s - loss: 0.1488 - 9ms/epoch - 4ms/step
Epoch 3/100
2/2 - 0s - loss: 0.1229 - 17ms/epoch - 8ms/step
Epoch 4/100
2/2 - 0s - loss: 0.1005 - 18ms/epoch - 9ms/step
Epoch 5/100
2/2 - 0s - loss: 0.0798 - 17ms/epoch - 8ms/step
Epoch 6/100
2/2 - 0s - loss: 0.0636 - 14ms/epoch - 7ms/step
Epoch 7/100
2/2 - 0s - loss: 0.0510 - 16ms/epoch - 8ms/step
Epoch 8/100
2/2 - 0s - loss: 0.0448 - 19ms/epoch - 9ms/step
Epoch 9/100
2/2 - 0s - loss: 0.0429 - 27ms/epoch - 13ms/step
Epoch 10/100
2/2 - 0s - loss: 0.0441 - 15ms/epoch - 8ms/step
Epoch 11/100
2/2 - 0s - loss: 0.0487 - 13ms/epoch - 7ms/step
Epoch 12/100
2/2 - 0s - loss: 0.0504 - 17ms/epoch - 8ms/step
Epoch 13/100
2/2 - 0s - loss: 0.0497 - 17ms/epoch - 8ms/step
Epoch 14/100
2/2 - 0s - loss: 0.0476 - 21ms/epoch - 10ms/step
Epoch 15/100
2/2 - 0s - loss: 0.0449 - 17ms/epoch - 8ms/step
Epoch 16/100
2/2 - 0s - loss: 0.0434 - 15ms/epoch - 8ms/step
Epoch 17/100
2/2 - 0s - loss: 0.0415 - 16ms/epo

In [16]:
# melakukan prediksi harga saham pada data uji
predictions = model.predict(x_test)
# predictions = scaler.inverse_transform(predictions)

1/1 [==============================] - 0s 26ms/step


In [17]:
predictions

array([[0.19166462],
       [0.5368268 ],
       [0.5280459 ],
       [0.22161125],
       [0.31874272],
       [0.17945506],
       [0.48463595],
       [0.6860228 ],
       [0.17689757],
       [0.46164772]], dtype=float32)

In [18]:
y_test

array([0.14285714, 0.57142857, 0.57142857, 0.04761905, 0.28571429,
       0.0952381 , 0.71428571, 0.76190476, 0.04761905, 0.33333333])